// Generated by scripts/stamp-world-version.mjs — do not edit by hand.
//
// The cache key for every world asset. World files carry a long cache header on paths
// that never change, so this is what makes a rebuilt world reach a returning player
// instead of waiting out their cache. It covers world.gltf, both buffers and
// roadnet.json, so changing any of them changes the key.
export const WORLD_ASSET_VERSION = "07eea5940efc";
