// GENERATED by scripts/export-plots.ts — do not edit by hand.
// Regenerate with: npm --prefix game run export:plots
//
// The fifteen trades as the authority runs them: what a cycle consumes, what it makes,
// how long it takes, and which of its outputs a household will buy at the counter.

export interface TradeSpec {
  key: string;
  name: string;
  durationSeconds: number;
  labourCost: number;
  inputs: Record<string, number>;
  output: Record<string, number>;
  wastePerCycle: number;
  servicePayout: number;
  retailItems: readonly string[];
}

export const TRADES: Record<string, TradeSpec> = {
  "aquaworks": {
    "key": "aquaworks",
    "name": "Tideglass AquaWorks",
    "durationSeconds": 18,
    "labourCost": 12,
    "inputs": {
      "power": 1,
      "part": 1
    },
    "output": {
      "water": 54
    },
    "wastePerCycle": 0,
    "servicePayout": 0,
    "retailItems": []
  },
  "sungrid": {
    "key": "sungrid",
    "name": "Sunwell Microgrid",
    "durationSeconds": 24,
    "labourCost": 18,
    "inputs": {
      "part": 2,
      "material": 2
    },
    "output": {
      "power": 98
    },
    "wastePerCycle": 0,
    "servicePayout": 0,
    "retailItems": []
  },
  "greenhouse": {
    "key": "greenhouse",
    "name": "Greenloom Greenhouse",
    "durationSeconds": 69,
    "labourCost": 52,
    "inputs": {
      "water": 11,
      "power": 6
    },
    "output": {
      "food": 23
    },
    "wastePerCycle": 6,
    "servicePayout": 0,
    "retailItems": [
      "food"
    ]
  },
  "mine": {
    "key": "mine",
    "name": "Stonewake Mine",
    "durationSeconds": 21,
    "labourCost": 19,
    "inputs": {
      "part": 2,
      "power": 3,
      "water": 2
    },
    "output": {
      "ore": 24
    },
    "wastePerCycle": 2,
    "servicePayout": 0,
    "retailItems": []
  },
  "timberworks": {
    "key": "timberworks",
    "name": "Timbercoast Works",
    "durationSeconds": 21,
    "labourCost": 17,
    "inputs": {
      "part": 2,
      "power": 2,
      "water": 2
    },
    "output": {
      "timber": 24
    },
    "wastePerCycle": 2,
    "servicePayout": 0,
    "retailItems": []
  },
  "cratemill": {
    "key": "cratemill",
    "name": "Freight Crate Mill",
    "durationSeconds": 12,
    "labourCost": 8,
    "inputs": {
      "timber": 2,
      "power": 1
    },
    "output": {
      "crate": 4
    },
    "wastePerCycle": 1,
    "servicePayout": 0,
    "retailItems": []
  },
  "workshop": {
    "key": "workshop",
    "name": "Maker Workshop",
    "durationSeconds": 22,
    "labourCost": 20,
    "inputs": {
      "ore": 4,
      "crate": 2,
      "power": 2
    },
    "output": {
      "part": 5
    },
    "wastePerCycle": 2,
    "servicePayout": 0,
    "retailItems": []
  },
  "factory": {
    "key": "factory",
    "name": "Mercedonian Factory",
    "durationSeconds": 33,
    "labourCost": 44,
    "inputs": {
      "ore": 8,
      "part": 3,
      "power": 5,
      "water": 3
    },
    "output": {
      "equipment": 8
    },
    "wastePerCycle": 5,
    "servicePayout": 0,
    "retailItems": []
  },
  "construction": {
    "key": "construction",
    "name": "Civic Construction Co.",
    "durationSeconds": 36,
    "labourCost": 54,
    "inputs": {
      "timber": 6,
      "part": 6,
      "equipment": 3
    },
    "output": {
      "material": 24
    },
    "wastePerCycle": 3,
    "servicePayout": 0,
    "retailItems": []
  },
  "freight": {
    "key": "freight",
    "name": "Copper Quay Freight",
    "durationSeconds": 19,
    "labourCost": 16,
    "inputs": {
      "crate": 2,
      "part": 2,
      "power": 3
    },
    "output": {},
    "wastePerCycle": 0,
    "servicePayout": 46,
    "retailItems": []
  },
  "shop": {
    "key": "shop",
    "name": "Supply Shop & Café",
    "durationSeconds": 12,
    "labourCost": 10,
    "inputs": {
      "food": 2,
      "crate": 1,
      "part": 1,
      "power": 1
    },
    "output": {
      "supply": 10
    },
    "wastePerCycle": 1,
    "servicePayout": 0,
    "retailItems": [
      "supply"
    ]
  },
  "restaurant": {
    "key": "restaurant",
    "name": "Sunset Market Kitchen",
    "durationSeconds": 12,
    "labourCost": 12,
    "inputs": {
      "food": 2,
      "supply": 1,
      "water": 1,
      "power": 1
    },
    "output": {},
    "wastePerCycle": 1,
    "servicePayout": 15,
    "retailItems": []
  },
  "gym": {
    "key": "gym",
    "name": "Harbor Gym",
    "durationSeconds": 14,
    "labourCost": 13,
    "inputs": {
      "supply": 1,
      "water": 1,
      "power": 1
    },
    "output": {},
    "wastePerCycle": 0,
    "servicePayout": 16,
    "retailItems": []
  },
  "cinema": {
    "key": "cinema",
    "name": "Lantern Cinema",
    "durationSeconds": 16,
    "labourCost": 17,
    "inputs": {
      "supply": 3,
      "power": 3
    },
    "output": {},
    "wastePerCycle": 0,
    "servicePayout": 16,
    "retailItems": []
  },
  "recycler": {
    "key": "recycler",
    "name": "Tideglass Reclamation Hub",
    "durationSeconds": 19,
    "labourCost": 19,
    "inputs": {
      "waste": 5,
      "power": 2
    },
    "output": {
      "material": 2,
      "part": 2
    },
    "wastePerCycle": 0,
    "servicePayout": 0,
    "retailItems": []
  }
};

export const TRADE_KEYS: readonly string[] = Object.keys(TRADES);
