/**
 * Generate the server's plot table from the client's world data.
 *
 * The server deliberately does not import client code — catalogue.ts mirrors the
 * economic constants by hand — but there are several hundred plots and hand-copying
 * them would go stale on the first world edit. This writes them instead, footfall
 * score included, so the tick loop can price a corner without knowing any geometry.
 *
 * Re-run after any change to the plot layout or to plotFootfall:
 *   npm --prefix game run export:plots
 */
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { BUSINESS, PLOTS, plotFootfall, RESOURCES, type LicenseKey } from "../game/src/data";

const workspace = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const rows = PLOTS.map((plot) => ({
  id: plot.id,
  island: plot.island,
  footfall: Number(plotFootfall(plot.id).toFixed(4)),
}));

const body = `// GENERATED by scripts/export-plots.ts — do not edit by hand.
// Regenerate with: npm --prefix game run export:plots
//
// The world's plots as the authority sees them: which district each sits in, and how
// busy its corner is. Footfall is baked at export rather than recomputed here so the
// server needs no world geometry to run the district.

export interface PlotSpec { id: string; island: string; footfall: number }

export const PLOTS: readonly PlotSpec[] = ${JSON.stringify(rows, null, 2)};

export const PLOTS_BY_ID: ReadonlyMap<string, PlotSpec> = new Map(PLOTS.map((plot) => [plot.id, plot]));

export const ISLAND_IDS: readonly string[] = [...new Set(PLOTS.map((plot) => plot.island))];
`;

const out = resolve(workspace, "server/src/plots.ts");
writeFileSync(out, body);
console.log(`plots exported: ${rows.length} across ${new Set(rows.map((r) => r.island)).size} districts -> server/src/plots.ts`);

// --- the trades themselves --------------------------------------------------
// The tick loop has to run production without trusting a client to say what it made,
// which means the authority needs the recipes. Same reasoning as the plots: fifteen
// trades with inputs, outputs and cycle times is too much to mirror by hand.
const trades = (Object.keys(BUSINESS) as LicenseKey[]).map((key) => {
  const config = BUSINESS[key];
  const retail = Object.keys(config.output).filter((item) => RESOURCES[item as keyof typeof RESOURCES]?.buyer === "citizens");
  return {
    key,
    name: config.name,
    durationSeconds: config.duration,
    labourCost: config.laborCost,
    inputs: config.inputs as Record<string, number>,
    output: config.output as Record<string, number>,
    wastePerCycle: config.wastePerCycle ?? 0,
    servicePayout: config.servicePayout ?? 0,
    // What households will buy over the counter. A mine makes ore; nobody's kitchen
    // wants ore, which is why the supply chain has retail on the end of it.
    retailItems: retail,
  };
});

const tradeBody = `// GENERATED by scripts/export-plots.ts — do not edit by hand.
// Regenerate with: npm --prefix game run export:plots
//
// The fifteen trades as the authority runs them: what a cycle consumes, what it makes,
// how long it takes, and which of its outputs a household will buy at the counter.

export interface TradeSpec {
  key: string;
  name: string;
  durationSeconds: number;
  labourCost: number;
  inputs: Record<string, number>;
  output: Record<string, number>;
  wastePerCycle: number;
  servicePayout: number;
  retailItems: readonly string[];
}

export const TRADES: Record<string, TradeSpec> = ${JSON.stringify(Object.fromEntries(trades.map((t) => [t.key, t])), null, 2)};

export const TRADE_KEYS: readonly string[] = Object.keys(TRADES);
`;
writeFileSync(resolve(workspace, "server/src/trades.ts"), tradeBody);
console.log(`trades exported: ${trades.length} -> server/src/trades.ts`);
