/**
 * Generate the server's plot table from the client's world data.
 *
 * The server deliberately does not import client code — catalogue.ts mirrors the
 * economic constants by hand — but there are several hundred plots and hand-copying
 * them would go stale on the first world edit. This writes them instead, footfall
 * score included, so the tick loop can price a corner without knowing any geometry.
 *
 * Re-run after any change to the plot layout or to plotFootfall:
 *   npm --prefix game run export:plots
 */
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { PLOTS, plotFootfall } from "../game/src/data";

const workspace = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const rows = PLOTS.map((plot) => ({
  id: plot.id,
  island: plot.island,
  footfall: Number(plotFootfall(plot.id).toFixed(4)),
}));

const body = `// GENERATED by scripts/export-plots.ts — do not edit by hand.
// Regenerate with: npm --prefix game run export:plots
//
// The world's plots as the authority sees them: which district each sits in, and how
// busy its corner is. Footfall is baked at export rather than recomputed here so the
// server needs no world geometry to run the district.

export interface PlotSpec { id: string; island: string; footfall: number }

export const PLOTS: readonly PlotSpec[] = ${JSON.stringify(rows, null, 2)};

export const PLOTS_BY_ID: ReadonlyMap<string, PlotSpec> = new Map(PLOTS.map((plot) => [plot.id, plot]));

export const ISLAND_IDS: readonly string[] = [...new Set(PLOTS.map((plot) => plot.island))];
`;

const out = resolve(workspace, "server/src/plots.ts");
writeFileSync(out, body);
console.log(`plots exported: ${rows.length} across ${new Set(rows.map((r) => r.island)).size} districts -> server/src/plots.ts`);
